### PR TITLE
Log to sentry by default

### PR DESCRIPTION
**Pull request by symroe**
I'm not 100% sure about `LOGGING["loggers"][""]` – will this catch too much? 

Otherwise, this is basically what we do with EE

### CODE REVIEW

**Comment by chris48s** [comment]
I reckon you're going to get every single deprecated django call etc logged to sentry if we catch every warning event in every module. I'd stick to catching the one event we want for now

**Comment by symroe** [comment]
Ok, updated

**Review by chris48s — APPROVED** [review]
that does look right, accepting I've not tested it

**Comment by symroe** [comment]
Let's see!

**Pull request merged**
